### ISSUE TITLE
Need simple LED Blink (Hello World of microcontroller world) example using Arduino

### ISSUE THREAD

**Issue by teslatickles** [teslatickles/micrometa#3]
Need an Arduino example of an LED blinking, including schematic, readme, and, of course, the appropriate code. This should be easy!

**Comment by rdeleonf** [comment]
Hi, I would like to work on this.
Is it ok? I can upload everything in around 5 mins.

**Comment by teslatickles** [comment]
@rdeleonf Absolutely!
